name: sar-antarctica
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.12.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.11.0
  - azure-storage-common-cpp=12.6.0
  - babel=2.14.0
  - bcrypt=4.1.3
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cairo=1.18.0
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colour=0.1.5
  - comm=0.2.2
  - contourpy=1.2.1
  - cryptography=42.0.8
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.0
  - freetype=2.12.1
  - freexl=2.0.0
  - furl=2.1.3
  - gdal=3.9.0
  - geoalchemy2=0.13.3
  - geos=3.12.1
  - geotiff=1.7.3
  - giflib=5.2.2
  - greenlet=3.0.3
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.2.1
  - importlib_metadata=7.2.1
  - infinity=1.5
  - intervals=0.9.2
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - json-c=0.17
  - jupyter=1.1.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libblas=3.9.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.9.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - lxml=5.2.2
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - multiprocess=0.70.16
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nspr=4.35
  - nss=3.101
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orderedmultidict=1.0.1
  - packaging=24.1
  - parso=0.8.4
  - passlib=1.7.4
  - pathos=0.3.2
  - pcre2=10.43
  - pendulum=3.0.0
  - pexpect=4.9.0
  - phonenumbers=8.13.39
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.2
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - pox=0.3.4
  - ppft=1.7.6.8
  - progressbar2=4.4.2
  - proj=9.4.1
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyrosar=0.23.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-utils=3.8.2
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - rasterio=1.3.10
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - setuptools=70.1.0
  - setuptools-scm=8.1.0
  - setuptools_scm=8.1.0
  - six=1.16.0
  - snappy=1.2.0
  - snuggs=1.4.7
  - spatialist=0.13.1
  - spdlog=1.13.0
  - sqlalchemy=1.4.49
  - sqlalchemy-utils=0.41.2
  - sqlalchemy-utils-arrow=0.41.2
  - sqlalchemy-utils-babel=0.41.2
  - sqlalchemy-utils-base=0.41.2
  - sqlalchemy-utils-color=0.41.2
  - sqlalchemy-utils-encrypted=0.41.2
  - sqlalchemy-utils-intervals=0.41.2
  - sqlalchemy-utils-password=0.41.2
  - sqlalchemy-utils-pendulum=0.41.2
  - sqlalchemy-utils-phone=0.41.2
  - sqlalchemy-utils-timezone=0.41.2
  - sqlalchemy-utils-url=0.41.2
  - sqlite=3.46.0
  - stack_data=0.6.2
  - tblib=3.0.0
  - tiledb=2.24.1
  - time-machine=2.14.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2024a
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - asf-search==7.1.3
      - boto3==1.34.132
      - botocore==1.34.132
      - ciso8601==2.3.1
      - dateparser==1.2.0
      - git+https://github.com/abradley60/dem-stitcher.git@dem_fill 
      - jmespath==1.0.1
      - pyproj==3.6.1
      - regex==2024.5.15
      - s3transfer==0.10.2
      - scipy==1.14.0
      - sentineleof==0.9.5
      - shapely==2.0.4
      - tenacity==8.2.2
      - tzlocal==5.2
      