name: Run Tests with Pytest

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run tests with pixi environment
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      uses: prefix-dev/setup-pixi@v0.8.3
      with:
        pixi-version: v0.44.0
        cache: true
    - run: pixi run pipeline_tests
